defaults: &defaults
  working_directory: ~/qmk

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
      - run:
          name: "Workaround `x509: failed to load system roots and no roots provided`"
          command: |
            echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list
            apt-get update
            apt-get install -y ca-certificates
      - run:
          name: Build keymap
          command: |
            mkdir /tmp/artifacts
            make git-submodule
            make clean && make planck/rev4:eiryu
            cp planck_rev4_eiryu.hex /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  main:
    jobs:
      - build
